kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: default
  labels:
    app: postgres
spec:
  storageClassName: nfs-medogz
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Public/postgres-pv
    server: 192.168.1.123
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: default
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
